//! Menu bar tray icon and reduced menu (DESIGN.md §6).
//!
//! [`Tray`] owns the `tray-icon` menu, kept to: "Allow Accessibility Access…" (+ separator, only
//! while access is missing), "Clean Screen"/"Clean Keyboard", a separator, "Settings…" (opens the
//! settings window), a separator, and "Quit". Every other former menu item (color, auto-unlock,
//! keyboard-only, show/hide icon, open at login, about, source code) now lives in the settings
//! window instead. Every visible label comes from [`crate::core::i18n::Text`].

use tray_icon::menu::{Menu, MenuEvent, MenuId, MenuItem, PredefinedMenuItem};
use tray_icon::{Icon, TrayIcon, TrayIconBuilder};

use crate::core::i18n::{Language, Text};
use crate::core::settings::Settings;

/// The embedded 36×36 raw RGBA menu bar icon (2x of 18 pt — DESIGN.md §2), generated by
/// `design/scripts/export-icons.sh` from `design/menubar-icon/menubar.svg`. No PNG decoder is
/// linked in: this is the raw pixel data, read directly.
const MENUBAR_ICON_RGBA: &[u8] = include_bytes!("../../assets/menubar-icon@2x.rgba");
/// Side length of [`MENUBAR_ICON_RGBA`] in pixels.
const MENUBAR_ICON_SIZE: u32 = 36;

/// Errors building or updating the tray icon/menu.
#[derive(Debug, thiserror::Error)]
pub enum TrayError {
    /// The embedded icon bytes could not be interpreted as RGBA (should never happen for the
    /// asset this crate ships — checked defensively rather than with `unwrap`).
    #[error("invalid embedded menu bar icon: {0}")]
    Icon(#[from] tray_icon::BadIcon),
    /// Building the menu or any of its items failed.
    #[error("failed to build the tray menu: {0}")]
    Menu(#[from] tray_icon::menu::Error),
    /// Creating the tray icon itself failed.
    #[error("failed to create the tray icon: {0}")]
    Tray(#[from] tray_icon::Error),
}

/// A command produced by a click on the reduced tray menu, decoded from a [`MenuEvent`] by
/// [`Tray::command_for`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayCommand {
    /// Opens System Settings on the Accessibility pane. Only present in the menu while
    /// Accessibility access is missing.
    GrantAccess,
    /// Start a cleaning session (screen or keyboard-only, depending on the current mode).
    Clean,
    /// Opens the settings window.
    Settings,
    /// Quit the app.
    Quit,
}

const ID_GRANT_ACCESS: &str = "grant_access";
const ID_CLEAN: &str = "clean";
const ID_SETTINGS: &str = "settings";
const ID_QUIT: &str = "quit";

/// Owns the menu bar tray icon and reduced menu, built per DESIGN.md §6.
pub struct Tray {
    icon: TrayIcon,
    language: Language,
    /// A cheap handle to the same native menu as `icon`'s (`muda::Menu` is a `Clone`-able
    /// reference type), kept around so [`Tray::update`] can insert/remove the "Allow
    /// Accessibility Access…" item and its separator as the permission state changes, without
    /// rebuilding the whole menu.
    menu: Menu,
    grant_access_item: MenuItem,
    grant_access_separator: PredefinedMenuItem,
    /// Whether `grant_access_item`/`grant_access_separator` are currently inserted into `menu`.
    grant_access_visible: bool,
    clean_item: MenuItem,
}

impl Tray {
    /// Builds and shows the tray icon/menu for `settings`/`language`. `trusted`
    /// (`permission::is_trusted()` at construction time) decides whether "Allow Accessibility
    /// Access…" starts out in the menu.
    ///
    /// # Errors
    ///
    /// Returns [`TrayError`] if the embedded icon is malformed, building the menu fails, or
    /// creating the tray icon itself fails.
    pub fn new(settings: &Settings, language: Language, trusted: bool) -> Result<Self, TrayError> {
        let icon = Icon::from_rgba(
            MENUBAR_ICON_RGBA.to_vec(),
            MENUBAR_ICON_SIZE,
            MENUBAR_ICON_SIZE,
        )?;

        let grant_access_item = MenuItem::with_id(
            ID_GRANT_ACCESS,
            Text::MenuGrantAccess.get(language),
            true,
            None,
        );
        let grant_access_separator = PredefinedMenuItem::separator();

        let clean_item = MenuItem::with_id(ID_CLEAN, clean_label(*settings, language), true, None);
        let settings_item =
            MenuItem::with_id(ID_SETTINGS, Text::MenuSettings.get(language), true, None);
        let quit_item = MenuItem::with_id(ID_QUIT, Text::MenuQuit.get(language), true, None);

        let menu = Menu::new();
        if !trusted {
            menu.append(&grant_access_item)?;
            menu.append(&grant_access_separator)?;
        }
        menu.append(&clean_item)?;
        menu.append(&PredefinedMenuItem::separator())?;
        menu.append(&settings_item)?;
        menu.append(&PredefinedMenuItem::separator())?;
        menu.append(&quit_item)?;

        let icon_handle = TrayIconBuilder::new()
            .with_menu(Box::new(menu.clone()))
            .with_icon(icon)
            .with_icon_as_template(true)
            .with_tooltip("Urahafu")
            .build()?;

        Ok(Self {
            icon: icon_handle,
            language,
            menu,
            grant_access_item,
            grant_access_separator,
            grant_access_visible: !trusted,
            clean_item,
        })
    }

    /// Refreshes the "Clean Screen"/"Clean Keyboard" label and the "Allow Accessibility Access…"
    /// item's presence, after `settings` or `trusted` changed elsewhere (the settings window, or
    /// the permission watcher observing a change).
    pub fn update(&mut self, settings: &Settings, trusted: bool) {
        if trusted && self.grant_access_visible {
            if let Err(err) = self.menu.remove(&self.grant_access_separator) {
                eprintln!("urahafu: failed to remove the grant-access menu separator: {err}");
            }
            if let Err(err) = self.menu.remove(&self.grant_access_item) {
                eprintln!("urahafu: failed to remove the grant-access menu item: {err}");
            }
            self.grant_access_visible = false;
        } else if !trusted && !self.grant_access_visible {
            if let Err(err) = self
                .menu
                .insert_items(&[&self.grant_access_item, &self.grant_access_separator], 0)
            {
                eprintln!("urahafu: failed to insert the grant-access menu item: {err}");
            }
            self.grant_access_visible = true;
        }

        self.clean_item
            .set_text(clean_label(*settings, self.language));
    }

    /// Access to the underlying `tray-icon` handle, if platform code needs it directly (e.g. to
    /// remove the icon on shutdown — dropping [`Tray`] already does this via `tray-icon`'s own
    /// `Drop` impl, so this is only for cases that need the handle itself).
    #[must_use]
    pub fn handle(&self) -> &TrayIcon {
        &self.icon
    }

    /// Decodes a [`MenuEvent`] into a [`TrayCommand`], or `None` if it does not match one of this
    /// menu's items (e.g. an event from an unrelated tray icon, in a process that has more than
    /// one).
    #[must_use]
    pub fn command_for(event: &MenuEvent) -> Option<TrayCommand> {
        let id: &MenuId = event.id();
        match id.as_ref() {
            ID_GRANT_ACCESS => Some(TrayCommand::GrantAccess),
            ID_CLEAN => Some(TrayCommand::Clean),
            ID_SETTINGS => Some(TrayCommand::Settings),
            ID_QUIT => Some(TrayCommand::Quit),
            _ => None,
        }
    }
}

/// The Clean item's dynamic label: "Clean Screen" normally, "Clean Keyboard" when keyboard-only
/// mode is active.
fn clean_label(settings: Settings, language: Language) -> &'static str {
    if settings.keyboard_only {
        Text::MenuCleanKeyboard.get(language)
    } else {
        Text::MenuCleanScreen.get(language)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clean_label_switches_with_keyboard_only() {
        let mut settings = Settings::default();
        assert_eq!(
            clean_label(settings, Language::ENGLISH),
            Text::MenuCleanScreen.get(Language::ENGLISH)
        );
        settings.keyboard_only = true;
        assert_eq!(
            clean_label(settings, Language::ENGLISH),
            Text::MenuCleanKeyboard.get(Language::ENGLISH)
        );
    }

    #[test]
    fn command_for_maps_every_known_id() {
        // `MenuEvent` has no public constructor in `muda`, so this test only checks the id
        // strings resolve through the same match `command_for` uses, exercised through the
        // public ids used when building the menu (the `ID_*` constants).
        let ids_and_commands = [
            (ID_GRANT_ACCESS, TrayCommand::GrantAccess),
            (ID_CLEAN, TrayCommand::Clean),
            (ID_SETTINGS, TrayCommand::Settings),
            (ID_QUIT, TrayCommand::Quit),
        ];
        let mut seen = std::collections::HashSet::new();
        for (id, expected) in ids_and_commands {
            assert!(seen.insert(id), "duplicate id constant: {id}");
            let event = MenuEvent {
                id: MenuId::new(id),
            };
            assert_eq!(Tray::command_for(&event), Some(expected));
        }
    }

    #[test]
    fn command_for_unknown_id_is_none() {
        let event = MenuEvent {
            id: MenuId::new("not-a-urahafu-menu-item"),
        };
        assert_eq!(Tray::command_for(&event), None);
    }
}
